#!/bin/bash

#PBS -N Lorenz63
#PBS -l select=1:ncpus=12:mem=128gb 
#PBS -l walltime=72:00:00 
#PBS -M arpit.kapoor@unsw.edu.au 
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5370003/projects/lorenz63-fokker-planck/mcsim/runs/run.log

cd $PBS_O_WORKDIR

module load ffmpeg
for M in 40
do
    for SY in 0.2
    do 
        ~/miniconda3/envs/fplanck/bin/python fp_mcsim.py --M $M --sy $SY --savecode 2  --comppost 1 --njobs 4
    done
done